export interface MediaAsset {
  id: string
  type: 'mp4' | 'mov' | 'gif' | 'png' | 'jpeg'
  src: string
  filename: string
  title: string
}

export const mediaAssets: MediaAsset[] = [
  // Images
  {
    id: 'jpeg-ace',
    type: 'jpeg',
    src: '/media/ace.jpeg',
    filename: 'ace.jpeg',
    title: 'Ace Jigglypuff',
  },
  {
    id: 'jpeg-detective',
    type: 'jpeg',
    src: '/media/Detective.JPEG',
    filename: 'Detective.JPEG',
    title: 'Detective Jigglypuff',
  },
  {
    id: 'jpeg-director',
    type: 'jpeg',
    src: '/media/Director.jpg',
    filename: 'Director.jpg',
    title: 'Director Jigglypuff',
  },
  {
    id: 'jpeg-locked-in',
    type: 'jpeg',
    src: '/media/locked in.jpeg',
    filename: 'locked in.jpeg',
    title: 'Locked In Jigglypuff',
  },
  {
    id: 'jpeg-one-piece',
    type: 'jpeg',
    src: '/media/OnePiece.jpeg',
    filename: 'OnePiece.jpeg',
    title: 'One Piece Jigglypuff',
  },
  {
    id: 'jpeg-starters',
    type: 'jpeg',
    src: '/media/Starters.jpg',
    filename: 'Starters.jpg',
    title: 'Starters',
  },
  {
    id: 'png-diamond',
    type: 'png',
    src: '/media/DiamondJiggly.png',
    filename: 'DiamondJiggly.png',
    title: 'Diamond Jigglypuff',
  },
  {
    id: 'png-hold',
    type: 'png',
    src: '/media/hold.png',
    filename: 'hold.png',
    title: 'Hold Jigglypuff',
  },
  {
    id: 'png-jesse',
    type: 'png',
    src: '/media/jesse jigglypuff.png',
    filename: 'jesse jigglypuff.png',
    title: 'Jesse Jigglypuff',
  },
  {
    id: 'png-jiggly-mustache',
    type: 'png',
    src: '/media/jiggly mustache.png',
    filename: 'jiggly mustache.png',
    title: 'Jigglypuff with Mustache',
  },
  {
    id: 'png-jigglybuff',
    type: 'png',
    src: '/media/jigglybuff.png',
    filename: 'jigglybuff.png',
    title: 'Jigglybuff',
  },
  {
    id: 'png-jk-logo-old',
    type: 'png',
    src: '/media/JK LOGO old.PNG',
    filename: 'JK LOGO old.PNG',
    title: 'JK Logo (Original)',
  },
  {
    id: 'png-jk-index',
    type: 'png',
    src: '/media/JKIndex.png',
    filename: 'JKIndex.png',
    title: 'JK Index',
  },
  {
    id: 'png-mcdonalds',
    type: 'png',
    src: '/media/mcdonaldsjiggly.png',
    filename: 'mcdonaldsjiggly.png',
    title: 'McDonald\'s Jigglypuff',
  },
  {
    id: 'png-sad',
    type: 'png',
    src: '/media/sad.png',
    filename: 'sad.png',
    title: 'Sad Jigglypuff',
  },
  {
    id: 'png-sad-close',
    type: 'png',
    src: '/media/sad close.png',
    filename: 'sad close.png',
    title: 'Sad Jigglypuff (Close Up)',
  },
  {
    id: 'png-jigglypudge',
    type: 'png',
    src: '/media/Jigglypudge.png',
    filename: 'Jigglypudge.png',
    title: 'Jigglypudge',
  },
  {
    id: 'gif-banner',
    type: 'gif',
    src: '/media/Jiggly banner.gif',
    filename: 'Jiggly banner.gif',
    title: 'Jigglypuff Banner',
  },
  {
    id: 'gif-explosion',
    type: 'gif',
    src: '/media/explosion.gif',
    filename: 'explosion.gif',
    title: 'Explosion',
  },
  // Videos
  {
    id: 'mp4-almost-got-us',
    type: 'mp4',
    src: '/media/almostgotus.mp4',
    filename: 'almostgotus.mp4',
    title: 'Almost Got Us',
  },
  {
    id: 'mp4-appearance',
    type: 'mp4',
    src: '/media/appearance.mp4',
    filename: 'appearance.mp4',
    title: 'Appearance',
  },
  {
    id: 'mp4-arrived',
    type: 'mp4',
    src: '/media/arrived.mp4',
    filename: 'arrived.mp4',
    title: 'Arrived',
  },
  {
    id: 'mp4-blue-opening',
    type: 'mp4',
    src: '/media/BLUEOPENING.mp4',
    filename: 'BLUEOPENING.mp4',
    title: 'Blue Opening',
  },
  {
    id: 'mp4-gn',
    type: 'mp4',
    src: '/media/gn.mp4',
    filename: 'gn.mp4',
    title: 'GN',
  },
  {
    id: 'mp4-hurt-again',
    type: 'mp4',
    src: '/media/hurtagain.mp4',
    filename: 'hurtagain.mp4',
    title: 'Hurt Again',
  },
  {
    id: 'mp4-jiggly-card',
    type: 'mp4',
    src: '/media/JIgglyCard.mp4',
    filename: 'JIgglyCard.mp4',
    title: 'Jigglypuff Card Animation',
  },
  {
    id: 'mp4-jiggly-history',
    type: 'mp4',
    src: '/media/jigglypuff history.mp4',
    filename: 'jigglypuff history.mp4',
    title: 'Jigglypuff History',
  },
  {
    id: 'mp4-jiggly-rorschach',
    type: 'mp4',
    src: '/media/JigglyRorschach.mp4',
    filename: 'JigglyRorschach.mp4',
    title: 'Jigglypuff Rorschach',
  },
  {
    id: 'mp4-jk-index-stadium',
    type: 'mp4',
    src: '/media/JKIndexStatdium.mp4',
    filename: 'JKIndexStatdium.mp4',
    title: 'JK Index Stadium',
  },
  {
    id: 'mp4-jk-index-bg',
    type: 'mp4',
    src: '/media/Jkinex bg moving.mp4',
    filename: 'Jkinex bg moving.mp4',
    title: 'JK Index Background',
  },
  {
    id: 'mp4-j-king',
    type: 'mp4',
    src: '/media/JKing.mp4',
    filename: 'JKing.mp4',
    title: 'Jigglypuff King',
  },
  {
    id: 'mp4-jk-song',
    type: 'mp4',
    src: '/media/JKSong.mp4',
    filename: 'JKSong.mp4',
    title: 'Jigglypuff Theme Song',
  },
  {
    id: 'mp4-jk-walking',
    type: 'mp4',
    src: '/media/JKWalking.mp4',
    filename: 'JKWalking.mp4',
    title: 'Jigglypuff Walking',
  },
  {
    id: 'mp4-serenade',
    type: 'mp4',
    src: '/media/serenade.mp4',
    filename: 'serenade.mp4',
    title: 'Serenade',
  },
  {
    id: 'mov-gm',
    type: 'mov',
    src: '/media/gm.MOV',
    filename: 'gm.MOV',
    title: 'GM',
  },
  {
    id: 'mov-hackerman',
    type: 'mov',
    src: '/media/hackerman jigglypuff.MOV',
    filename: 'hackerman jigglypuff.MOV',
    title: 'Hackerman Jigglypuff',
  },
  {
    id: 'mov-jiggly-montage',
    type: 'mov',
    src: '/media/jigglymontage.MOV',
    filename: 'jigglymontage.MOV',
    title: 'Jigglypuff Montage',
  },
  {
    id: 'mov-merry-christmas',
    type: 'mov',
    src: '/media/merry christmas.MOV',
    filename: 'merry christmas.MOV',
    title: 'Merry Christmas',
  },
  {
    id: 'mov-index',
    type: 'mov',
    src: '/media/Index.MOV',
    filename: 'Index.MOV',
    title: 'Index',
  },
]
